//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Czlowiek
    {
        public int Id_C { get; set; }
        public string imie { get; set; }
        public int wiek { get; set; }
        public double wzrost { get; set; }

        public override string ToString()
        {
            return imie;
        }
    }
}
